name: klavierapp_frontend
description: Klavier Flutter frontend (scaffold)
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.2
  provider: ^6.1.1
  jwt_decode: ^0.3.1
  file_picker: ^8.0.0
  intl: ^0.20.2
  flutter_quill: ^11.5.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
