version: "3.8"
services:
  db_prod:
    build:
      context: .
      dockerfile: deploy/postgres.Dockerfile
    command: >
      postgres -c shared_preload_libraries=pg_cron -c cron.database_name=${POSTGRES_DB}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_prod_data:
